<a href="https://colab.research.google.com/github/tarunkumar910/ai_project/blob/main/fake_news_predication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing the dependecies

import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import nltk

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [4]:
# printing the stopwords in english
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [6]:
# loading the data set to a pandas dataframe

news_dataset = pd.read_csv('/content/FakeNewsNet.csv')

In [7]:
news_dataset.shape

(23196, 5)

In [8]:
# print the first 5 dataframe
news_dataset.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

In [10]:
# counting the number of label
news_dataset['real'].value_counts()

real
1    17441
0     5755
Name: count, dtype: int64

In [11]:
#counting the number of missing value
news_dataset.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [12]:
# replacing the null values with empty string
news=news_dataset.fillna('')

In [14]:
news.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

In [15]:
news.isnull().sum()

title            0
news_url         0
source_domain    0
tweet_num        0
real             0
dtype: int64

In [16]:
# mearging the title and soucre domain

news['content']=news['title']+' '+news['source_domain']

In [17]:
news.head()

,title,news_url,source_domain,tweet_num,real,content
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1,Kandi Burruss Explodes Over Rape Accusation on...
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1,People's Choice Awards 2018: The best red carp...
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1,Sophia Bush Sends Sweet Birthday Message to 'O...
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1,Colombian singer Maluma sparks rumours of inap...
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1,Gossip Girl 10 Years Later: How Upper East Sid...

In [18]:
print(news['content'])

0        Kandi Burruss Explodes Over Rape Accusation on...
1        People's Choice Awards 2018: The best red carp...
2        Sophia Bush Sends Sweet Birthday Message to 'O...
3        Colombian singer Maluma sparks rumours of inap...
4        Gossip Girl 10 Years Later: How Upper East Sid...
                               ...
23191    Pippa Middleton wedding: In case you missed it...
23192    Zayn Malik & Gigi Hadid’s Shocking Split: Why ...
23193    Jessica Chastain Recalls the Moment Her Mother...
23194    Tristan Thompson Feels "Dumped" After Khloé Ka...
23195    Kelly Clarkson Performs a Medley of Kendrick L...
Name: content, Length: 23196, dtype: object

In [20]:
# sperating the data and label

X=news.drop(columns='real',axis=1)
Y=news['real']

In [22]:

# printing the x and y


print(X)
print(Y)

                                                   title  \
0      Kandi Burruss Explodes Over Rape Accusation on...
1      People's Choice Awards 2018: The best red carp...
2      Sophia Bush Sends Sweet Birthday Message to 'O...
3      Colombian singer Maluma sparks rumours of inap...
4      Gossip Girl 10 Years Later: How Upper East Sid...
...                                                  ...
23191  Pippa Middleton wedding: In case you missed it...
23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...
23193  Jessica Chastain Recalls the Moment Her Mother...
23194  Tristan Thompson Feels "Dumped" After Khloé Ka...
23195  Kelly Clarkson Performs a Medley of Kendrick L...

                                                news_url  \
0      http://toofab.com/2017/05/08/real-housewives-a...
1      https://www.today.com/style/see-people-s-choic...
2      https://www.etonline.com/news/220806_sophia_bu...
3      https://www.dailymail.co.uk/news/article-33655...
4      https://www.zerchoo.com/entertainment/gossip-g...
...                                                  ...
23191  https://www.express.co.uk/news/royal/807049/pi...
23192  hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...
23193  http://www.justjared.com/2018/01/17/jessica-ch...
23194  www.intouchweekly.com/posts/tristan-thompson-f...
23195  https://www.billboard.com/articles/news/bbma/8...

               source_domain  tweet_num  \
0                 toofab.com         42
1              www.today.com          0
2           www.etonline.com         63
3        www.dailymail.co.uk         20
4            www.zerchoo.com         38
...                      ...        ...
23191      www.express.co.uk         52
23192      hollywoodlife.com          7
23193      www.justjared.com         26
23194  www.intouchweekly.com         24
23195      www.billboard.com         85

                                                 content
0      Kandi Burruss Explodes Over Rape Accusation on...
1      People's Choice Awards 2018: The best red carp...
2      Sophia Bush Sends Sweet Birthday Message to 'O...
3      Colombian singer Maluma sparks rumours of inap...
4      Gossip Girl 10 Years Later: How Upper East Sid...
...                                                  ...
23191  Pippa Middleton wedding: In case you missed it...
23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...
23193  Jessica Chastain Recalls the Moment Her Mother...
23194  Tristan Thompson Feels "Dumped" After Khloé Ka...
23195  Kelly Clarkson Performs a Medley of Kendrick L...

[23196 rows x 5 columns]
0        1
1        1
2        1
3        1
4        1
        ..
23191    1
23192    0
23193    1
23194    0
23195    1
Name: real, Length: 23196, dtype: int64

Steaming process

it is the process of reducing the  word to its root word

actting acteor actes -> act

In [23]:
port_stem =PorterStemmer()

In [24]:
from nltk.corpus.reader import StreamBackedCorpusView
def stemming (content):
  stemmed_content=re.sub('[^a-zA-Z]',' ',content)
  stemmed_content=stemmed_content.lower()
  stemmed_content=stemmed_content.split()
  stemmed_content=[port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content=' '.join(stemmed_content)

  return stemmed_content

In [25]:
 news['content']=news['content'].apply(stemming)

In [26]:
print(news['content'])

0        kandi burruss explod rape accus real housew at...
1        peopl choic award best red carpet look www tod...
2        sophia bush send sweet birthday messag one tre...
3        colombian singer maluma spark rumour inappropr...
4        gossip girl year later upper east sider shock ...
                               ...
23191    pippa middleton wed case miss pippa marri lace...
23192    zayn malik gigi hadid shock split chanc reunit...
23193    jessica chastain recal moment mother boyfriend...
23194    tristan thompson feel dump khlo kardashian ref...
23195    kelli clarkson perform medley kendrick lamar h...
Name: content, Length: 23196, dtype: object

In [27]:
# seprating the the title and source domain
X=news['content'].values
Y=news['real'].values

In [29]:
Y.shape

(23196,)

In [30]:
# conveting the textual data to numerical data

vectorizer =TfidfVectorizer()
vectorizer.fit(X)

X=vectorizer.transform(X)

In [31]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 246417 stored elements and shape (23196, 14435)>
  Coords	Values
  (0, 59)	0.2597097788538541
  (0, 651)	0.30737565657585053
  (0, 1707)	0.38749399933436923
  (0, 2460)	0.0508218665886508
  (0, 4193)	0.35506164978733906
  (0, 5891)	0.26124620267491605
  (0, 6647)	0.38749399933436923
  (0, 10223)	0.302158398468634
  (0, 10276)	0.23128301802698967
  (0, 10569)	0.2543303205934995
  (0, 12980)	0.2946734912504806
  (0, 13681)	0.21108934405813046
  (1, 729)	0.3083771474680274
  (1, 1101)	0.33844294892026705
  (1, 1916)	0.3875096512688879
  (1, 2219)	0.42251489448694257
  (1, 2460)	0.08159478582438673
  (1, 7432)	0.33284454859410584
  (1, 9476)	0.23697414575567807
  (1, 10347)	0.37702288594702094
  (1, 12946)	0.36817044163275126
  (1, 14274)	0.10189043319535993
  (2, 1201)	0.19486226938688445
  (2, 1530)	0.3779018214766305
  (2, 1711)	0.3321987353251551
  :	:
  (23194, 4387)	0.2692478125672807
  (23194, 5800)	0.2632849856372537
  (23194, 6240)	0.28925922464908643
  (23194, 6661)	0.17479540394859372
  (23194, 6797)	0.28785051901050934
  (23194, 6994)	0.26381957644897924
  (23194, 7230)	0.30870481533818256
  (23194, 8384)	0.2822154791515417
  (23194, 10393)	0.31860580642240854
  (23194, 12818)	0.26985982917564694
  (23194, 13154)	0.2717482205740398
  (23194, 14274)	0.06617170360348418
  (23195, 729)	0.18257216480989652
  (23195, 1167)	0.44359883337472966
  (23195, 2318)	0.27348859087437083
  (23195, 2460)	0.04830752475490311
  (23195, 5754)	0.2561748235324755
  (23195, 5941)	0.3819332333944831
  (23195, 6732)	0.23172295312137026
  (23195, 6749)	0.33243273972601206
  (23195, 7037)	0.2988459804176233
  (23195, 7960)	0.3500409208295561
  (23195, 8457)	0.21409156547616323
  (23195, 9497)	0.23609444741706065
  (23195, 14274)	0.060323396576666556

In [32]:
# creating train and text data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify=Y, random_state=2)

In [33]:
# traning the model
model=LogisticRegression()

In [34]:
# trainnig the data
model.fit(X_train,Y_train)

LogisticRegression()

In [35]:
# now thw accuracy of the model

X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print(training_data_accuracy)

0.8827333477042466

In [36]:
# now the accuracy of the model in test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print(test_data_accuracy)

0.8525862068965517